development:
  clients:
    default:
      database: mongo_react_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
        user: 'root'
        password: 'rootpassword'
        auth_source: admin
        auth_mech: :scram

test:
  clients:
    default:
      database: mongo_react_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        user: 'root'
        password: 'rootpassword'
        auth_source: admin
        auth_mech: :scram
        max_pool_size: 1
